######################################################################
# Automatically generated by qmake (2.01a) zo nov 11 14:52:38 2007
######################################################################

TEMPLATE = app
TARGET = 3dsplay
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl
LIBS += -l3ds -lglut -lGL -lSDL -lSDL_image
CONFIG += debug

# Input
HEADERS += q3dstools.h 
SOURCES += main.cpp
